# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json, package-lock.json, and tsconfig.json
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000
EXPOSE 3001

# Start the application
CMD ["npm", "run", "dev"]
